version: '3'

services:
  coinmena-db:
    image: postgres
    env_file: .env
    volumes:
      - dbdata:/var/lib/postgresql/data
  coinmena:
    container_name: coinmena
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/coinmena
    depends_on:
      - coinmena-db
    env_file: .env
    links:
      - coinmena-db:coinmena-db

volumes:
  dbdata:
