# Generated by Django 3.2.3 on 2021-07-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField(max_length=100)),
                ("code", models.TextField(max_length=20)),
                (
                    "status",
                    models.BooleanField(default=True, help_text="Current coin Status"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField(max_length=100)),
                ("code", models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ExchangeRateLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField(max_length=100)),
                ("code", models.TextField(max_length=20)),
                (
                    "request_status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Unknown state"),
                            (2, "The exchange rate received"),
                            (3, "The request pending"),
                            (4, "The exchange rate request failed"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "asking_price",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                (
                    "bid_price",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("last_refreshed", models.DateTimeField(blank=True, null=True)),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.coin"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.currency"
                    ),
                ),
            ],
        ),
    ]
