# Generated by Django 3.2.3 on 2021-07-01 23:50

from django.db import migrations, models


def setup_initial_data(apps, schema_editor):
    Coin = apps.get_model("main", "Coin")
    Currency = apps.get_model("main", "Currency")

    coin, _ = Coin.objects.get_or_create(name="Bit Coin", code="BTC")
    currency, _ = Currency.objects.get_or_create(name="US Dollars", code="USD")


def reverse_initial_data(apps, schema_editor):
    Coin = apps.get_model("main", "Coin")
    Currency = apps.get_model("main", "Currency")
    ExchangeRateLogs = apps.get_model("main", "ExchangeRateLogs")

    ExchangeRateLogs.objects.all().delete()
    Coin.objects.all().delete()
    Currency.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangeratelogs",
            name="code",
        ),
        migrations.RemoveField(
            model_name="exchangeratelogs",
            name="name",
        ),
        migrations.AddField(
            model_name="exchangeratelogs",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="exchangeratelogs",
            name="message",
            field=models.TextField(
                blank=True, help_text="Response/error message can be saved here"
            ),
        ),
        migrations.RunPython(
            code=setup_initial_data,
            reverse_code=reverse_initial_data
        ),
    ]
